(source melpa)

(depends-on "cask")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "s")
(depends-on "shut-up")
(depends-on "zenburn-theme")
(depends-on "zenburn-theme")