(source melpa)
(source gnu)
(source marmalade)

(depends-on "ace-jump-mode")
(depends-on "ag")
(depends-on "cask")
(depends-on "epl")
(depends-on "magit")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "shut-up")
(depends-on "zenburn-theme")
(depends-on "nyan-mode")
(depends-on "rainbow-delimiters")
(depends-on "yaml-mode")
(depends-on "exec-path-from-shell")
